# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f3zeJYXJwcvJoqIKU8cBjQ3NfsD4zIBw
"""

from dataclasses import dataclass
from scipy.integrate import solve_ivp
import numpy as np

@dataclass
class parameters:
  """
  Classe que armazena os parâmetros do bioreator.

  Vmax_r : Velocidade máxima de referência (mg/L.h)
  T_r : Temperatura de referência (K)
  Km : Constante de Michaelis-Menten (mg/L)
  Ea : Energia de ativação (J/mol)
  R : Constante dos gases ideal (J/mol.K)
  """

  Vmax_r : float = 5
  T_r : float = 298.15
  Km : float = 20
  Ea : float = 30000
  R : float = 8.314

def arrhenius(T, prmtrs):
  """
  Função que calcula a velocidade máxima em uma dada temperatura com base
  em uma referência conhecida dos parâmetros.

  T : Temperatura (K)
  prmtrs : Parâmetros do bioreator
  """

  Vmax_r = prmtrs.Vmax_r
  T_r = prmtrs.T_r
  Km = prmtrs.Km
  Ea = prmtrs.Ea
  R = prmtrs.R

  Vmax = Vmax_r * np.exp(-(Ea/R) * ((1/T) - (1/T_r)))

  return Vmax

def model(t, S, T, prmtrs):
  """
  Modelo diferêncial que descreve o comportamento da concentração do
  substrato no tempo.

  t : Instante de tempo (h)
  S : Concentração do substrato (mg/L)
  T : Temperatura (K)
  prmtrs : Parâmetros do bioreator
  """

  Km = prmtrs.Km

  Vmax = arrhenius(T, prmtrs)

  dSdt = -Vmax * S / (Km + S)

  return dSdt

def simulation(t_i, t_f, N, T, S_0=100, prmtrs=None):
  """
  Função que simula o comportamento da concentração do substrato no tempo
  com base na equação diferêncial do modelo.

  t_i : Instante de tempo inicial (h)
  t_f : Instante de tempo final (h)
  S_0 : Concentração inicial do substrato (mg/L)
  T : Temperatura (K)
  prmtrs : Parâmetros do bioreator
  """
  if prmtrs == None:
    prmtrs = parameters()

  # Encapsulando o modelo
  sim_model = lambda t, S: model(t, S, T, prmtrs)

  # Resolvendo a equação diferencial
  res = solve_ivp(sim_model, [t_i, t_f], [S_0], t_eval=np.linspace(t_i, t_f, N))

  return res.t, res.y[0]